' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json.Linq

Namespace BitcoinAverage


    Friend Class Ticker
        Public Property avg_24h As Double
        Public Property ask As Double
        Public Property bid As Double
        Public Property last As Double
        Public Property timestamp As String
        Public Property total_vol As Double
    End Class

End Namespace

